Routes:
  - UpstreamPathTemplate: '/{url}'
    DownstreamPathTemplate: '/{url}'
    DownstreamScheme: http
    DownstreamHostAndPorts:
      - Host: localhost
        Port: 5003
    UpstreamHttpMethod:
      - Get
GlobalConfiguration:
  BaseUrl: 'http://localhost:5000'
  #add ServiceDiscoveryProvider Consul
  ServiceDiscoveryProvider:
    Host: 172.16.3.119
    Port: 8500
    Type: Consul
  #add ServiceDiscoveryProvider Consul(also need to add eureka section in appsetting.yml)
  #ServiceDiscoveryProvider:
  #  Type: Eureka