apiVersion: v1
kind: Namespace
metadata:
 name: dotnetcore

#************** hei-ocelot-api ************* #
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: hei-ocelot-api
 namespace: dotnetcore
spec:
 replicas: 1
 selector:
  matchLabels:
   app: hei-ocelot-api
 template:
  metadata:
   labels:
    app: hei-ocelot-api
  spec:
   containers:
    - name: hei-ocelot-api
      image: gebiwangshushu/hei-ocelot-api:1.0
      ports:
       - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
 name: hei-ocelot-api
 namespace: dotnetcore
spec:
 type: NodePort
 ports:
  - port: 80
    targetPort: 80
    nodePort: 31003
 selector:
  app: hei-ocelot-api

#************** hei-ocelot-identityserver ************* #
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: hei-ocelot-identityserver
 namespace: dotnetcore
spec:
 replicas: 1
 selector:
  matchLabels:
   app: hei-ocelot-identityserver
 template:
  metadata:
   labels:
    app: hei-ocelot-identityserver
  spec:
   containers:
    - name: hei-ocelot-identityserver
      image: gebiwangshushu/hei-ocelot-identityserver:1.0
      ports:
       - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
 name: hei-ocelot-identityserver
 namespace: dotnetcore
spec:
 type: NodePort
 ports:
  - port: 80
    targetPort: 80
    nodePort: 31100
 selector:
  app: hei-ocelot-identityserver


#************** hei-ocelot-apigateway ************* #
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: hei-ocelot-apigateway 
 namespace: dotnetcore
spec:
 replicas: 1
 selector:
  matchLabels:
   app: hei-ocelot-apigateway 
 template:
  metadata:
   labels:
    app: hei-ocelot-apigateway 
  spec:
   containers:
    - name: hei-ocelot-apigateway 
      #image: gebiwangshushu/hei-ocelot-apigateway:1.0
      image: 172.16.1.31:5000/hei-ocelot-apigateway:1.1
      ports:
       - containerPort: 80
      volumeMounts:
       - name: hei-ocelot-apigateway
         mountPath: "/app/config"
         readOnly: true
   volumes:
    - name: hei-ocelot-apigateway
      configMap:
       name: hei-ocelot-apigateway

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hei-ocelot-apigateway
  namespace: dotnetcore
data:
  appsettings.yml: |
    Logging:
      LogLevel:
        Default: Information
        Microsoft: Warning
        Microsoft.Hosting.Lifetime: Information
    AllowedHosts: '*'
    AddAdministration:
      Path: /administration
      IdentityServer:
        Authority: 'http://172.16.1.30:31100'
        ApiName: ocelot
        RequireHttpsMetadata: false
        ApiSecret: secret
  ocelot.yml: |
    Routes:
      - UpstreamPathTemplate: '/{url}'
        DownstreamPathTemplate: '/{url}'
        DownstreamScheme: http
        DownstreamHostAndPorts:
          - Host: localhost
            Port: 5003
        UpstreamHttpMethod:
          - Get
    GlobalConfiguration:
        BaseUrl: 'http://localhost:5000'

---
kind: Service
apiVersion: v1
metadata:
 name: hei-ocelot-apigateway 
 namespace: dotnetcore
spec:
 type: NodePort
 ports:
  - port: 80
    targetPort: 80
    nodePort: 31500
 selector:
  app: hei-ocelot-apigateway 