apiVersion: v1
kind: Namespace
metadata:
 name: aspnetcore

# hei-ocelot-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: hei-ocelot-api
 namespace: aspnetcore
spec:
 replicas: 1
 selector:
  matchLabels:
   app: hei-ocelot-api
 template:
  metadata:
   labels:
    app: hei-ocelot-api
  spec:
   containers:
    - name: hei-ocelot-api
      image: 172.16.1.31:5000/hei-ocelot-k8s:v13k8sfixed
      ports:
       - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
 name: hei-ocelot-api
 namespace: aspnetcore
spec:
 type: NodePort
 ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
 selector:
  app: hei-ocelot-api

# hei-ocelot-identityserver


# hei-ocelot-apigateway