apiVersion: v1
kind: Namespace
metadata:
 name: aspnetcore

# hei-ocelot-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: hei-ocelot-api
 namespace: aspnetcore
spec:
 replicas: 1
 selector:
  matchLabels:
   app: hei-ocelot-api
 template:
  metadata:
   labels:
    app: hei-ocelot-api
  spec:
   containers:
    - name: hei-ocelot-api
      image: 172.16.1.31:5000/hei-ocelot-k8s:v13k8sfixed
      ports:
       - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
 name: hei-ocelot-api
 namespace: aspnetcore
spec:
 type: NodePort
 ports:
  - port: 80
    targetPort: 80
    nodePort: 35003
 selector:
  app: hei-ocelot-api



# hei-ocelot-identityserver


# hei-ocelot-apigateway

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-configmap
data:
  appsettings.yml: |
    Logging:
      LogLevel:
        Default: Information
        Microsoft: Warning
        Microsoft.Hosting.Lifetime: Information
    AllowedHosts: '*'
    AddAdministration:
      Path: /administration
      IdentityServer:
        Authority: 'http://172.16.3.117:5100'
        ApiName: ocelot
        RequireHttpsMetadata: false
        ApiSecret: secret